Documentation:
  Enabled: false
Layout/LineLength:
  Max: 110
AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - 'spec/lib/**/*'
    - 'spec/lib/*'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/BlockLength:
  CountComments: false
  Max: 25
